export const MODEL_PRESETS = [
  {
    id: "openai-balance",
    provider: "OpenAI",
    label: "GPT linh hoạt",
    model: "gpt-5.4-mini",
    baseUrl: "",
    costLabel: "Tính phí theo mức sử dụng API",
    note: "Lựa chọn mặc định cho phần lớn tác vụ biên tập hằng ngày.",
  },
  {
    id: "openai-quality",
    provider: "OpenAI",
    label: "GPT chuyên sâu",
    model: "gpt-5.5",
    baseUrl: "",
    costLabel: "Chi phí cao hơn",
    note: "Phù hợp với yêu cầu cần đọc dữ liệu kỹ và lập luận sâu.",
  },
  {
    id: "openai-cheap",
    provider: "OpenAI",
    label: "GPT nhanh gọn",
    model: "gpt-5.4-nano",
    baseUrl: "",
    costLabel: "Chi phí thấp hơn",
    note: "Phù hợp để tạo bản nháp hoặc thử nhiều phương án ngắn.",
  },
  {
    id: "gemini-flash",
    provider: "Google Gemini",
    label: "Gemini Flash",
    model: "gemini-3.5-flash",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta/openai",
    costLabel: "Có hạn mức miễn phí, vượt hạn mức sẽ tính phí",
    note: "Tốc độ tốt, phù hợp khi cần thử nhiều bản nội dung.",
  },
  {
    id: "gemini-lite",
    provider: "Google Gemini",
    label: "Gemini Flash-Lite",
    model: "gemini-3.1-flash-lite",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta/openai",
    costLabel: "Có hạn mức miễn phí, vượt hạn mức sẽ tính phí",
    note: "Ưu tiên tốc độ và chi phí khi tạo nhiều phương án.",
  },
  {
    id: "gemini-pro",
    provider: "Google Gemini",
    label: "Gemini Pro",
    model: "gemini-3.1-pro",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta/openai",
    costLabel: "Tùy hạn mức của tài khoản",
    note: "Dành cho yêu cầu cần phân tích dữ liệu đầu vào kỹ hơn.",
  },
  {
    id: "openrouter",
    provider: "OpenRouter",
    label: "OpenRouter",
    model: "openai/gpt-5.4-mini",
    baseUrl: "https://openrouter.ai/api/v1",
    costLabel: "Chi phí phụ thuộc mô hình được chọn",
    note: "Kết nối nhiều mô hình khác nhau qua cùng một API.",
  },
  {
    id: "ollama",
    provider: "Ollama trên máy",
    label: "Mô hình cục bộ",
    model: "llama3.1",
    baseUrl: "http://localhost:11434/v1",
    costLabel: "Không tính phí API, sử dụng tài nguyên máy",
    note: "Cần cài Ollama và tải mô hình trước khi sử dụng.",
  },
];

export function applyModelPreset(currentSettings, preset) {
  return {
    ...currentSettings,
    model: preset.model,
    baseUrl: preset.baseUrl,
  };
}
